### ISSUE TITLE
No module named "lib"

### ISSUE THREAD

**Issue by suvaansh** [yangshao/Commonsense4Action#1]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-66a082261cb9> in <module>
----> 1 a = pickle.load(open("gold_test_samples.pkl", "rb"))

ModuleNotFoundError: No module named 'lib'

There is an error in your pkl files. They require a lib file or some lib.data file to unpickle.

**Comment by yangshao** [comment]
Hi,  In this project, we use dill(https://pypi.org/project/dill/) instead of pickle to load the dataset. So you can try to use 
 dill.load(open("gold_test_samples.pkl", "rb"))

**Comment by suvaansh** [comment]
Hello,

I tried "dill" too. I believe there is some environment issue. There is
some different version of lib you are using. Can you please send me the
details of the python environment you were using while serializing
those files?

Kind regards,
Suvaansh Bhambri

**Comment by yangshao** [comment]
can you paste the full error trace when you use dill?

**Comment by suvaansh** [comment]
Sure, here it is.

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
(env2) suvaansh@suvaansh-U2002:~/CJAR/Commonsense4Action$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> f = dill.load(open("gold_test_samples.pkl", "rb"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/home/suvaansh/anaconda3/envs/env2/lib/python3.7/site-packages/dill/_dill.py",
line 305, in load
    obj = pik.load()
  File
"/home/suvaansh/anaconda3/envs/env2/lib/python3.7/site-packages/dill/_dill.py",
line 474, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'lib'
>>>
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Kind regards,
Suvaansh Bhambri

**Comment by suvaansh** [comment]
Hi Yangshao

Did you look into the problem?

**Comment by yangshao** [comment]
@suvaansh I'm working on to transform the binary file to textural file. Once it's done, I will let you know.

**Comment by suvaansh** [comment]
@yangshao Thanks!

**Comment by yangshao** [comment]
@suvaansh I've added the json files and corresponding descriptions in the readme file. If you have any problem, please let me know.

**Comment by suvaansh** [comment]
@yangshao Thanks you for your help!

**Comment by lengyuner** [comment]
https://www.jianshu.com/p/66213833ed15

'lib' is the folder or  'py' file name of the project. The error is reported because  the pickle data of load contains a object defined in the 'py' file in, but it is not defined in your code.
